sudo: require

matrix:
  include:

    - os: linux
      dist: xenial
      compiler: gcc
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7

    # Xcode 10.1 (10B61)
    # Apple LLVM version 10.0.0 (clang-1000.11.45.5)
    # Target: x86_64-apple-darwin18.2.0
    # Thread model: posix
    # InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      language: cpp

install:
  # upgrade python and cmake
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew upgrade python; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew upgrade cmake; fi

before_script:
  - if [ $TRAVIS_OS_NAME == linux ]; then export CC=gcc-7 && export CXX=g++-7; fi

  - ld -v
  - cmake --version
  - python --version
  - python3 --version

  - if [ $TRAVIS_OS_NAME == linux ]; then gcc --version; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then g++ --version; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then gcc-7 --version; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then g++-7 --version; fi

  - if [ $TRAVIS_OS_NAME == osx ]; then clang --version; fi
  
script:
  - git clone https://github.com/TzuChieh/Photon-v2-ThirdParty.git
  - bash ./setup.sh
  - mkdir -p ./build/
  - cd ./build/

  - cmake -DCMAKE_BUILD_TYPE=release -DBUILD_ENGINE_TEST=ON ../ 
  #- make -j4 VERBOSE=1
  - make -j4

  # Run engine unit test (working directory should be "./build/")
  - ./bin/EngineTest