#pragma once

#define PH_DEBUG
#define PH_ABORT_ON_ASSERTION_FAILED

#define PH_RENDER_MODE_RGB
//#define PH_RENDER_MODE_SPECTRAL
//#define PH_RENDER_MODE_FULL_SPECTRAL

#define PH_INTERSECTION_PROBE_DEPTH 8
#define PH_INTERSECTION_PROBE_REAL_CACHE_SIZE 8