#include <DataIO/SDL/Introspect/TOwnerSdlStruct.h>

#include <gtest/gtest.h>

using namespace ph;

namespace
{
	struct EmptyStruct
	{};
}

// It is known that compiling TOwnerSdlStruct with EmptyStruct in 
// VS2017 15.9.34 will cause warning C5046 which is about dtor not being 
// implemented; however, its dtor should be generated by compiler. This issue 
// is fixed in VS2019, see the reference for more info.
//
// reference: 
// https://developercommunity.visualstudio.com/t/undocumented-warning-c5046-symbol-involving-type-w/288509#T-N313128

TEST(SdlStructTest, DefaultStates)
{
	{
		TOwnerSdlStruct<EmptyStruct> sdlStruct("test-struct");
		EXPECT_EQ(sdlStruct.numFields(), 0);
		EXPECT_EQ(sdlStruct.getFields().numFields(), 0);

		// Getting non-existent fields is allowed and the result will be nullptr
		for(std::size_t fieldIdx = 0; fieldIdx < 1024; ++fieldIdx)
		{
			EXPECT_TRUE(sdlStruct.getField(fieldIdx) == nullptr);
			EXPECT_TRUE(sdlStruct.getFields().getField(fieldIdx) == nullptr);
		}
	}
}

// TODO: add field and add struct
