#pragma once

#include "Render/Imgui/Font/IconsMaterialDesignIcons.h"

#define PH_IMGUI_PROPERTIES_ICON       ICON_MDI_TUNE
#define PH_IMGUI_VIEWPORT_ICON         ICON_MDI_CAMERA_IRIS
#define PH_IMGUI_ASSET_ICON            ICON_MDI_FOLDER_OPEN
#define PH_IMGUI_OBJECTS_ICON          ICON_MDI_SHAPE
#define PH_IMGUI_OBJECT_ICON           ICON_MDI_CUBE
#define PH_IMGUI_SCENE_CREATION_ICON   ICON_MDI_IMAGE_PLUS
#define PH_IMGUI_SCENE_MANAGER_ICON    ICON_MDI_FOREST
#define PH_IMGUI_TASK_MANAGER_ICON     ICON_MDI_DESKTOP_CLASSIC
#define PH_IMGUI_LOG_ICON              ICON_MDI_CONSOLE
#define PH_IMGUI_SETTINGS_ICON         ICON_MDI_COG
#define PH_IMGUI_STATS_ICON            ICON_MDI_CHART_TIMELINE_VARIANT_SHIMMER
#define PH_IMGUI_SAVE_FILE_ICON        ICON_MDI_CONTENT_SAVE
#define PH_IMGUI_OPEN_FILE_ICON        ICON_MDI_FOLDER_OPEN
#define PH_IMGUI_CREATE_OBJECT_ICON    ICON_MDI_SHAPE_PLUS
#define PH_IMGUI_BUG_ICON              ICON_MDI_LADYBUG
#define PH_IMGUI_GENERAL_FILE_ICON     ICON_MDI_FILE_DOCUMENT
#define PH_IMGUI_NOTIFICATION_ICON     ICON_MDI_MESSAGE_ALERT
#define PH_IMGUI_VISIBLE_ICON          ICON_MDI_EYE
#define PH_IMGUI_INVISIBLE_ICON        ICON_MDI_EYE_OFF
#define PH_IMGUI_ARROW_LEFT_ICON       ICON_MDI_ARROW_LEFT_THICK
#define PH_IMGUI_ARROW_RIGHT_ICON      ICON_MDI_ARROW_RIGHT_THICK
#define PH_IMGUI_EXPAND_ICON           ICON_MDI_PLUS_BOX
#define PH_IMGUI_PLUS_ICON             ICON_MDI_PLUS
#define PH_IMGUI_LOADING_ICON          ICON_MDI_TIMER_SAND

#define PH_IMGUI_ICON_TIGHT_PADDING " "
#define PH_IMGUI_ICON_LOOSE_PADDING "   "
