#pragma once

#include "Engine/Math/TVector2.h"
#include "Engine/Math/TVector3.h"
#include "Engine/Math/Color/Spectrum.h"
#include "Engine/Core/Quantity/TimeStep.h"

#include <Common/assertion.h>
#include <Common/primitive_type.h>

#include <cstddef>

namespace ph { class RigidTransform; }
namespace ph { class SampleFlow; }

namespace ph
{

class Ray;
class RayDifferential;

/*! @brief A target that can receive any physical quantity, typically electromagnetic energy.
The received energy is originated from some `Emitter`s.
*/
class Receiver
{
public:
	Receiver(const RigidTransform* receiverToWorld, TimeStep timeStep, std::size_t numRaySampleDims);

	inline virtual ~Receiver() = default;

	/*! @brief Generate a ray received by the receiver.

	Given raster coordinates, generate a corresponding ray that would have
	hit that location from the light entry of the receiver. The light entry
	would be the outmost surface of a camera's lens system for example. This
	method is for Monte-Carlo sampling.

	@param sampleFlow Sample stream for receiver-owned ray dimensions.
	@param out_ray The generated ray.
	@return A weighting factor for the received quantity. Proper sensor response
	and sampling PDF are included in the returned weight.
	*/
	virtual math::Spectrum receiveRay(
		const math::Vector2D& rasterCoord,
		SampleFlow& sampleFlow,
		Ray* out_ray) const = 0;

	// Given a ray generated by receiveRay() along with the parameters for it, 
	// calculates differential information on the origin of the ray.
	// The default implementation uses numerical differentiation for 
	// the differentials.
	/*virtual void calcSensedRayDifferentials(const math::Vector2R& filmNdcPos, const Ray& sensedRay,
	                                        RayDifferential* out_result) const;*/

	virtual void evalEmittedImportanceAndPdfW(const math::Vector3R& targetPos, math::Vector2R* const out_filmCoord, math::Vector3R* const out_importance, real* out_filmArea, real* const out_pdfW) const = 0;

	/*! @brief Number of dimensions needed for one ray sample.
	Includes receiver-specific dimensions consumed by `receiveRay()` and scene time sampling if present.
	*/
	std::size_t numRaySampleDims() const;

	const TimeStep& getTimeStep() const;
	const RigidTransform& getReceiverToWorld() const;

private:
	const RigidTransform* m_receiverToWorld;
	TimeStep              m_timeStep;
	std::size_t           m_numRaySampleDims;
};

// In-header Implementations:

inline std::size_t Receiver::numRaySampleDims() const
{
	return m_numRaySampleDims;
}

inline const TimeStep& Receiver::getTimeStep() const
{
	return m_timeStep;
}

inline const RigidTransform& Receiver::getReceiverToWorld() const
{
	PH_ASSERT(m_receiverToWorld);

	return *m_receiverToWorld;
}

}// end namespace ph
