/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class core_Ph */

#ifndef _Included_core_Ph
#define _Included_core_Ph
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     core_Ph
 * Method:    printTestMessage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_core_Ph_printTestMessage
  (JNIEnv *, jclass);

/*
 * Class:     core_Ph
 * Method:    genTestHdrFrame
 * Signature: (Lcore/FloatArrayRef;Lcore/IntRef;Lcore/IntRef;)V
 */
JNIEXPORT void JNICALL Java_core_Ph_genTestHdrFrame
  (JNIEnv *, jclass, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
