/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class photonApi_Ph */

#ifndef _Included_photonApi_Ph
#define _Included_photonApi_Ph
#ifdef __cplusplus
extern "C" {
#endif
#undef photonApi_Ph_PH_BRUTE_FORCE_RENDERER_TYPE
#define photonApi_Ph_PH_BRUTE_FORCE_RENDERER_TYPE 1L
#undef photonApi_Ph_PH_IMPORTANCE_RENDERER_TYPE
#define photonApi_Ph_PH_IMPORTANCE_RENDERER_TYPE 2L
#undef photonApi_Ph_PH_HDR_FRAME_TYPE
#define photonApi_Ph_PH_HDR_FRAME_TYPE 50L
#undef photonApi_Ph_PH_DEFAULT_CAMERA_TYPE
#define photonApi_Ph_PH_DEFAULT_CAMERA_TYPE 100L
/*
 * Class:     photonApi_Ph
 * Method:    phStart
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_photonApi_Ph_phStart
  (JNIEnv *, jclass);

/*
 * Class:     photonApi_Ph
 * Method:    phExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_photonApi_Ph_phExit
  (JNIEnv *, jclass);

/*
 * Class:     photonApi_Ph
 * Method:    phCreateRenderer
 * Signature: (LphotonApi/LongRef;I)V
 */
JNIEXPORT void JNICALL Java_photonApi_Ph_phCreateRenderer
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     photonApi_Ph
 * Method:    phDeleteRenderer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_photonApi_Ph_phDeleteRenderer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     photonApi_Ph
 * Method:    phCreateCamera
 * Signature: (LphotonApi/LongRef;III)V
 */
JNIEXPORT void JNICALL Java_photonApi_Ph_phCreateCamera
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     photonApi_Ph
 * Method:    phDeleteCamera
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_photonApi_Ph_phDeleteCamera
  (JNIEnv *, jclass, jlong);

/*
 * Class:     photonApi_Ph
 * Method:    phCreateWorld
 * Signature: (LphotonApi/LongRef;)V
 */
JNIEXPORT void JNICALL Java_photonApi_Ph_phCreateWorld
  (JNIEnv *, jclass, jobject);

/*
 * Class:     photonApi_Ph
 * Method:    phDeleteWorld
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_photonApi_Ph_phDeleteWorld
  (JNIEnv *, jclass, jlong);

/*
 * Class:     photonApi_Ph
 * Method:    phCreateRenderTask
 * Signature: (LphotonApi/LongRef;JJJJ)V
 */
JNIEXPORT void JNICALL Java_photonApi_Ph_phCreateRenderTask
  (JNIEnv *, jclass, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     photonApi_Ph
 * Method:    phDeleteRenderTask
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_photonApi_Ph_phDeleteRenderTask
  (JNIEnv *, jclass, jlong);

/*
 * Class:     photonApi_Ph
 * Method:    phRunRenderTask
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_photonApi_Ph_phRunRenderTask
  (JNIEnv *, jclass, jlong);

/*
 * Class:     photonApi_Ph
 * Method:    printTestMessage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_photonApi_Ph_printTestMessage
  (JNIEnv *, jclass);

/*
 * Class:     photonApi_Ph
 * Method:    genTestHdrFrame
 * Signature: (LphotonApi/FloatArrayRef;LphotonApi/IntRef;LphotonApi/IntRef;)V
 */
JNIEXPORT void JNICALL Java_photonApi_Ph_genTestHdrFrame
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     photonApi_Ph
 * Method:    phCreateFrame
 * Signature: (LphotonApi/LongRef;III)V
 */
JNIEXPORT void JNICALL Java_photonApi_Ph_phCreateFrame
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     photonApi_Ph
 * Method:    phDeleteFrame
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_photonApi_Ph_phDeleteFrame
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
