#pragma once

#include "Core/Intersectable/Intersectable.h"

#include <vector>
#include <memory>

namespace ph
{

class Intersectable;
class Emitter;

/*! @brief A group of cooked data. Typically generated by `Actor`.
This data block do not persist throughout the rendering process. After cooking is done, all cooked data
should be properly interlinked and `CookedUnit` will be cleaned up.
*/
class CookedUnit final
{
public:
	std::vector<const Intersectable*> intersectables;
	std::unique_ptr<Emitter> emitter;
};

}// end namespace ph
