#include "Engine/Core/HitDetail.h"
#include "Engine/Math/hash.h"

#include <limits>
#include <type_traits>

namespace ph
{

// A simple value type should be trivially copyable
static_assert(std::is_trivially_copyable_v<HitDetail>);

HitDetail::HitDetail()
	: m_primitive                  (nullptr)
	, m_uvw                        (0, 0, 0)
	, m_rayT                       (std::numeric_limits<real>::max())
	, m_hitInfos                   {HitInfo{}, HitInfo{}}
	, m_faceID                     (NO_FACE_ID)
	, m_globalPrimitiveID          (0)
	, m_faceTopology               (EFaceTopology::General)
	, m_meanDistanceErrorFactor    (0x1p-64f)// ~= 5.42*10^-20, small enough to fail fast
	, m_maxDistanceErrorFactor     (0x1p-64f)
{}

HitDetail& HitDetail::setHitIntrinsics(
	const Primitive* const primitive,
	const math::Vector3R&  uvw,
	const real             rayT,
	const uint64           faceID,
	const FaceTopology     faceTopology)
{
	m_primitive    = primitive;
	m_uvw          = uvw;
	m_rayT         = rayT;
	m_faceID       = faceID;
	m_faceTopology = faceTopology;

	// Global primitive ID is generated by combining hashes incrementally on each stack of the probe.
	// Here is the initial hash, which is expected to be updated to distinguish between primitives.
	m_globalPrimitiveID = math::moremur_bit_mix_64(reinterpret_cast<uint64>(primitive));

	return *this;
}

void HitDetail::computeBases()
{
	for(HitInfo& hitInfo : m_hitInfos)
	{
		hitInfo.computeBases();
	}
}

void HitDetail::computeBasesOf(ECoordSys coordSys)
{
	m_hitInfos[enum_to_value(coordSys)].computeBases();
}

void HitDetail::setFlippedGeometryNormal()
{
	m_hitInfos[enum_to_value(ECoordSys::World)].setFlippedGeometryNormal();

	constexpr EFaceTopology curvatureFlags = EFaceTopology::Convex | EFaceTopology::Concave;
	PH_ASSERT(!m_faceTopology.hasAll(curvatureFlags));
	if(m_faceTopology.hasAny(curvatureFlags))
	{
		// Toggle between curvatures
		m_faceTopology.set(static_cast<EFaceTopology>(m_faceTopology.get() ^ enum_to_value(curvatureFlags)));
	}
}

uint64 HitDetail::getGlobalFaceID() const
{
	if(m_globalPrimitiveID == NO_FACE_ID)
	{
		return NO_FACE_ID;
	}

	return math::combine_hashes(
		m_globalPrimitiveID,
		math::moremur_bit_mix_64(getFaceID()));
}

}// end namespace ph
